---
# Name your file secrets.yml

development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  GITHUB_TOKEN: create_github_token

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  GITHUB_TOKEN: create_github_token

production:
  GITHUB_TOKEN: create_github_token